# Stage 1: Build React app
FROM node:20 AS build
WORKDIR /app

# Copy package.json + package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy toàn bộ source
COPY . .

# Build React app (sản phẩm ra /app/dist)
RUN npm run build
