services:
  backend:
    image: khoakhoa2004/notes-backend:latest
    container_name: notes-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/notesdb
      SPRING_DATASOURCE_USERNAME: notesuser
      SPRING_DATASOURCE_PASSWORD: notespass
    depends_on:
      - db
    networks:
      - notes-net
    restart: always
    expose:
      - "8080"

  frontend:
    image: khoakhoa2004/notes-frontend:latest
    container_name: notes-frontend
    depends_on:
      - backend
    networks:
      - notes-net
    command: ["true"]  # không chạy, chỉ để pull image
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
    restart: "no"

  nginx:
    image: nginx:latest
    container_name: notes-nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_dist:/usr/share/nginx/html:ro
    networks:
      - notes-net
    restart: always

networks:
  notes-net:
    driver: bridge

volumes:
  db_data:
  frontend_dist:

