services:
  db:
    image: mysql:5.7
    container_name: notes-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notesdb
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notespass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - notes-net
    restart: always

  backend:
    build: ./backend
    container_name: notes-backend
    image: khoakhoa2004/notes-backend:latest
    depends_on:
      - db
    networks:
      - notes-net
    restart: always

  frontend:
    build: ./frontend
    container_name: notes-frontend
    image: khoakhoa2004/notes-frontend:latest
    depends_on:
      - backend
    networks:
      - notes-net
    restart: always

networks:
  notes-net:
    driver: bridge

volumes:
  db_data:
