services:
  mysql-ci:
    image: mysql:8.0
    container_name: mysql-ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes_ci
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
