services:
  db:
    image: mysql:8.0
    container_name: notes-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notesdb
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notespass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: notes-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/notesdb
      SPRING_DATASOURCE_USERNAME: notesuser
      SPRING_DATASOURCE_PASSWORD: notespass
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./frontend
    container_name: notes-frontend
    depends_on:
      - backend
    environment:
    - VITE_API_URL=http://backend:8080/api
    ports:
      - "5173:80"

volumes:
  db_data:
