services:
  db:
    ports:
        - "3307:3306"

  backend:
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/backend
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/notesdb
      - SPRING_DATASOURCE_USERNAME=notesuser
      - SPRING_DATASOURCE_PASSWORD=notespass

  frontend:
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - VITE_API_URL=http://backend:8080/api
