spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notes_ci
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update   # hoặc create-drop nếu muốn mỗi lần test reset DB
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: false   # nếu bạn chưa dùng Flyway migration trong CI
